import * as dotenv from "dotenv";

dotenv.config();

export async function generateReview(analysisResults) {
  try {
    console.log(`\n✍️ Generating code review from analysis...\n`);

    // Build the review from analysis results intelligently
    let reviewContent = '';

    // Summary
    if (analysisResults.summary.total_issues === 0) {
      reviewContent += '## ✅ Code Review\n\n';
      reviewContent += `Great work! I analyzed ${analysisResults.files_analyzed} file(s) and found no critical issues. The code changes look clean and follow best practices.\n\n`;
    } else {
      reviewContent += '## 🔍 Code Review Summary\n\n';
      reviewContent += `I analyzed ${analysisResults.files_analyzed} file(s) and found **${analysisResults.summary.total_issues} issue(s)**:\n`;
      reviewContent += `- 🔴 Critical: ${analysisResults.summary.critical}\n`;
      reviewContent += `- 🟡 Warnings: ${analysisResults.summary.warnings}\n`;
      reviewContent += `- 💡 Suggestions: ${analysisResults.summary.suggestions}\n\n`;
    }

    // Critical Issues
    const criticalIssues = analysisResults.issues.filter(i => i.severity === 'Critical');
    if (criticalIssues.length > 0) {
      reviewContent += '### 🔴 Critical Issues\n\n';
      criticalIssues.forEach((issue, idx) => {
        reviewContent += `**${idx + 1}. ${issue.issue}**\n`;
        reviewContent += `- **File:** \`${issue.file}:${issue.line}\`\n`;
        reviewContent += `- **Type:** ${issue.type}\n`;
        reviewContent += `- **Why it matters:** ${issue.why}\n`;
        reviewContent += `- **How to fix:** ${issue.suggestion}\n\n`;
      });
    }

    // Warnings
    const warnings = analysisResults.issues.filter(i => i.severity === 'Warning');
    if (warnings.length > 0) {
      reviewContent += '### 🟡 Warnings\n\n';
      warnings.forEach((issue, idx) => {
        reviewContent += `**${idx + 1}. ${issue.issue}**\n`;
        reviewContent += `- **File:** \`${issue.file}:${issue.line}\`\n`;
        reviewContent += `- **Why it matters:** ${issue.why}\n`;
        reviewContent += `- **Suggestion:** ${issue.suggestion}\n\n`;
      });
    }

    // Suggestions
    const suggestions = analysisResults.issues.filter(i => i.severity === 'Suggestion');
    if (suggestions.length > 0) {
      reviewContent += '### 💡 Suggestions for Improvement\n\n';
      suggestions.forEach((issue, idx) => {
        reviewContent += `**${idx + 1}. ${issue.issue}**\n`;
        reviewContent += `- **File:** \`${issue.file}:${issue.line}\`\n`;
        reviewContent += `- **Suggestion:** ${issue.suggestion}\n\n`;
      });
    }

    // Closing
    reviewContent += '---\n\n';
    reviewContent += '## Next Steps\n\n';
    if (analysisResults.summary.total_issues > 0) {
      reviewContent += '1. Address critical issues first\n';
      reviewContent += '2. Review and implement warning fixes\n';
      reviewContent += '3. Consider suggestions for code quality improvements\n';
      reviewContent += '4. Push updates and request re-review\n\n';
    } else {
      reviewContent += '✅ No required changes. This PR is ready to merge!\n\n';
    }

    reviewContent += `**Review generated by:** pr-analyzer-agent\n`;
    reviewContent += `**Repository:** ${analysisResults.repository}\n`;
    reviewContent += `**PR:** #${analysisResults.pr_number}\n`;
    reviewContent += `**Files analyzed:** ${analysisResults.files_analyzed}\n`;

    const result = {
      status: "success",
      review: reviewContent,
      pr_number: analysisResults.pr_number,
      repository: analysisResults.repository,
      issues_found: analysisResults.summary.total_issues,
      timestamp: new Date().toISOString()
    };

    console.log("✨ Review generated successfully!");
    return result;

  } catch (error) {
    console.error(`❌ Error generating review: ${error.message}`);
    throw error;
  }
}

// Test function
if (import.meta.url === `file://${process.argv[1]}`) {
  const mockAnalysis = {
    pr_number: 123,
    repository: "owner/repo",
    pr_title: "Fix authentication bug",
    pr_author: "developer",
    files_analyzed: 3,
    summary: {
      total_issues: 5,
      critical: 2,
      warnings: 2,
      suggestions: 1
    },
    issues: [
      {
        file: "src/auth.js",
        line: 45,
        type: "Security",
        severity: "Critical",
        issue: "Password stored in plaintext",
        why: "Passwords must never be stored unencrypted",
        suggestion: "Use bcrypt for password hashing"
      },
      {
        file: "src/database.js",
        line: 120,
        type: "Security",
        severity: "Critical",
        issue: "SQL injection vulnerability",
        why: "String concatenation in queries allows injection attacks",
        suggestion: "Use parameterized queries"
      }
    ]
  };

  generateReview(mockAnalysis).then(result => {
    console.log("\n📋 Full Review:");
    console.log(result.review);
  }).catch(err => {
    console.error("Review generation failed:", err.message);
  });
}